#!/usr/bin/env python3
"""One-shot ingest of the 2026-06-04 blogs drop (7 net-new reviews).

- Adds 7 hand-authored English articles (observer/brand voice) to the sprint file.
- Registers the 7 slugs in blog-slugs-list.json + the source map.
- Archives the 2 duplicate scrapes (Sonic Boom Pro, Thunder 100 II) the user chose to skip.
blog.ts blogSlugs is edited separately. blog-articles.json is regenerated by blog:import.
"""
from __future__ import annotations
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPRINT = ROOT / "scripts/blog-main-sprint-articles.json"
SLUGS = ROOT / "scripts/blog-slugs-list.json"
SMAP = ROOT / "scripts/blog-slug-source-map.json"
BLOGS = ROOT / "blogs"
ARCHIVE = BLOGS / "_archive"
DATE = "2026-06-04"
CTA = "Not sure which racket fits your game? Try the finder quiz for a transparent, fit-scored shortlist."

# slug -> source .md filename (the Chinese forum scrape)
SOURCE_MAP = {
    "yonex-nanospeed-9900-ltg-green-sword-review": "【神兵利器】尤尼克斯-NS-9900-LTG-青剑-神兵利器.md",
    "yonex-voltric-z-force-ltd-2012-review": "【神兵利器】尤尼克斯-VT-ZF-LTD-紫金大姐夫-神兵利器.md",
    "gosen-ryoga-shiden-review": "【神兵利器】高神-Ryoga-Shiden-初代凌驾紫电.md",
    "victor-fz-100xx-budget-attack-review": "平替安赛龙，这支平价进攻拍太能打-胜利佛斩-FZ-100XX实战测评.md",
    "anta-ah600w-racket-review": "（猎奇920）安踏AH600W——有效的精神赔偿必然建立在深刻的精神创.md",
    "bonny-leisu-800-lt-review": "（猎奇1050）波力雷速800LT——八百雷霆-神兵利器.md",
    "mizuno-carbo-pro-825-review": "（猎奇1110）美津浓carbo-pro-825——柿子先涩后甜.md",
}

ARCHIVE_FILES = [
    "古怪开箱｜挥拍一击，音爆随后-胜利「音爆Pro」-神兵利器.md",  # dup of victor-sonic-boom-pro-budget-attack-review
    "（猎奇980）李宁雷霆100二代——迅捷与威力-神兵利器.md",       # dup of li-ning-thunder-100-gen-2-vs-gen-1
]

def sec(h, b):
    return {"heading": h, "body": " ".join(b.split())}

ARTICLES = [
    {
        "slug": "yonex-nanospeed-9900-ltg-green-sword-review",
        "updatedAt": DATE,
        "title": "Yonex NanoSpeed 9900 LTG (Green Sword) review: the rarest 2011 grail still plays",
        "dek": "The 2011 London Worlds limited Green Sword is the rarer half of the NS9900 LTD pair: a 3U frame that handles like 3.5U, with a firmer shaft and the line's signature fast, forgiving drive game.",
        "verdict": "A genuinely good-playing classic that has become a collector piece. If you want the feel rather than the badge, a standard NS9900 or a modern head-light speed racket gets you most of the way for a fraction of the asking price.",
        "sections": [
            sec("Why the Green Sword is the rare one", """
            Yonex released the NanoSpeed 9900 Limited as a paired set for the 2011 London World Championships, and only the green LT colourway was held back to a single 2011 run with no later reissue. That makes surviving examples far scarcer than the purple sibling, which is most of why prices have drifted into grail territory. The community reviewer is candid that a lot of the appeal is heritage and finish rather than on-court advantage: the silver-grey-to-teal gradient, the cross-weave throat pattern and the London 2011 marking are the draw. We have flagged this as a collector evaluation, not a current-market buying recommendation, because the racket is long discontinued and only trades second hand.
            """),
            sec("Build, weight and setup", """
            The tested frame is a 3U, but with grommets, cushion film, grip and string fitted it came in at roughly 90 grams, which the reviewer notes feels closer to a 3.5U in hand than a true 3U. The shaft is stiffer than the standard NS9900, and the example here was strung with a hard, crisp vertical-and-cross combination in the high-20s pounds. The takeaway for a buyer is that this is not a heavy bruiser: it sits between weight classes and rewards timing over muscle. If you already like fast head-light frames, the loading will feel familiar; if you come from a head-heavy attacker, expect to supply your own pace.
            """),
            sec("Drives and defence: the signature strength", """
            Flat exchanges are where the 9900 line earned its reputation, and the reviewer says the Green Sword pushes that further. The low swing weight and very quick handling let you sit half a beat ahead of an opponent in mid-court drives. Unlike the purple version's pure touch-and-go speed, this one pairs the fast release with a firmer, more planted feel, so block returns and counter-drives stay controlled rather than skittish. Defence is a highlight: the light head lifts easily into position, and the stiff shaft and solid frame return enough energy to push a smash back to the rear court, or even counter-attack, from a passive position.
            """),
            sec("Net play, drops and the smash question", """
            The larger frame and generous sweet spot make slice and check drops consistent, which helps disguise, and net touches are forgiving enough that a slightly off-centre contact does not blow up into an error. Pushes and net kills are quick. On the smash, the reviewer pushes back on the assumption that a head-light frame cannot hit: the Green Sword does not deliver the one-punch weight of a Voltric, but it strings together fast, accurate, repeatable smashes that are hard to read. For most club and league players that continuous pressure is more useful than raw single-hit power, and the frame keeps that up without tiring the arm.
            """),
            sec("Who should actually buy one", """
            The reviewer's most useful line is that the racket does not depend on your form: on a tired or off day it still produces a stable level, which is the real charm of the 9900 platform. That makes it a lovely racket to own and play. As a purchase, though, be honest about why. If you want a fast, forgiving, all-court head-light frame to actually compete with, a current speed flagship delivers comparable handling, a warranty and string support for far less money. Chase the Green Sword only if the 2011 heritage and the colourway are the point, and buy from a seller who can prove authenticity given the prices involved.
            """),
        ],
        "cta": CTA,
    },
    {
        "slug": "yonex-voltric-z-force-ltd-2012-review",
        "updatedAt": DATE,
        "title": "Yonex Voltric Z-Force LTD (2012) review: the 'Purple-Gold' grail, fourteen years on",
        "dek": "The 2012 London Olympics limited Voltric Z-Force LTD is a Lee Chong Wei-era attack icon. The 4U version (about 88g) is a surprisingly all-court frame, if you can load its brutally stiff shaft.",
        "verdict": "An extreme, high-threshold attacker with fragile paint and a heavy collector premium. Worth it only for committed attacking players who can genuinely load a 100ZZ-class shaft, and who value the heritage as much as the play.",
        "sections": [
            sec("The racket that defined violent attack", """
            Yonex built the Voltric Z-Force LTD as a 2012 London Olympics limited edition, and it became shorthand for top-end smashing in its era as Lee Chong Wei's weapon at his peak. The purple-gold-white gradient is widely regarded as one of Yonex's finest limited finishes, complete with the 2012 Limited marking and laser Z lettering. As with the other grails in this batch, the reviewer treats it as a heritage evaluation rather than a live recommendation: it is discontinued, trades second hand at inflated prices, and the paint is notoriously delicate. Buy on condition and provenance, not on the legend alone.
            """),
            sec("The 4U surprise", """
            The popular image of this racket is a 3U single-handed cannon for specialists only. The reviewer's 4U/G4 example reframes that: fully set up it weighed about 88 grams, in line with a modern 4U attacker, and that lighter head turns it into a genuine all-court frame rather than a one-dimensional bludgeon. It keeps the brutal attacking ceiling while adding enough manoeuvrability for continuous play and flat drives that you would not expect from the Voltric name. For a buyer, the practical message is that the 4U is the more usable version for doubles and mixed all-court games, where the 3U asks for more strength than most amateurs can sustain.
            """),
            sec("Smash: weight and continuity together", """
            Smashing is the whole point, and the reviewer breaks the appeal into three parts. Heavy smashes do not have the absolute one-hit demolition of the 3U, but land with concentrated, accurate weight that floors most amateur opponents. The underrated trait is the soft press: with the well-judged head weight you can lean on a steep half-court push without full effort, and chain those together relentlessly. Point smashes are fast with awkward placement, especially on a crisp string. Crucially, recovery after a smash is quick rather than laggy, and the frame does not punish a long, high-intensity session with arm fatigue, so you can hold attacking pressure across a full match.
            """),
            sec("Clears, net and the honest deal-breaker", """
            The pleasant shock is the clears: the reviewer rates them among the most effortless of any racket played, thanks to the shaft elasticity and head weight, with passive rear-court returns rescued on frame momentum alone. Drops and net work are better than the small old-frame reputation suggests, with clear feedback and a slightly larger sweet spot than the VTZF2. But the deal-breaker is real and unsolvable: the shaft is in Yonex's stiffest historic tier, in the class of the 100ZZ and Astrox 99, with almost no flex. If your power is not concentrated and whip-timed, it transmits nothing to the shuttle, jars the hand, and risks wrist and shoulder strain. The 4U does not lower that threshold; it only lowers swing weight.
            """),
            sec("Buy advice", """
            This is a love-and-hate racket: the violence, speed, looks and unique feedback on one side, the punishing threshold and fragile finish on the other. For the player who can drive it, the attacking payoff is hard to replace, and that is the honest case for owning one. For everyone else, a modern stiff attacker such as an Astrox 99 Pro delivers a similar ceiling with current support and a warranty, without the second-hand premium or the eggshell paint. If the heritage is what you want, target the 4U, insist on proof of authenticity, and accept that you are buying a piece of history as much as a match tool.
            """),
        ],
        "cta": CTA,
    },
    {
        "slug": "gosen-ryoga-shiden-review",
        "updatedAt": DATE,
        "title": "Gosen Ryoga Shiden review: the cult conical-shaft speed blade, decoded",
        "dek": "The first-generation Ryoga Shiden ('Blue-Purple Lightning') is Gosen's Zylon-and-Aermet conical-shaft 3U: a tiny sweet spot, the brand's hardest shaft, and arguably the best point-smash feel ever made.",
        "verdict": "An extreme, unforgiving speed blade that has become a high-premium collector item. Sublime for precise, full-power attackers; punishing for anyone who cannot consistently find a very small sweet spot.",
        "sections": [
            sec("A genuine cult classic", """
            Gosen is best known in the West for strings, but its Ryoga racket line earned a cult following, and the first-generation Shiden is the most legendary entry. The blue-to-white finish with the flowing calligraphic name still looks high-end today, and the transparent shaft showing the carbon weave reads like a piece of craftsmanship rather than a mass-market frame. The reviewer is upfront about the usual old-Gosen weakness: the paint and stickers are fragile, picking up press marks from stringing and chipping easily. As with the other grails here, we treat this as a heritage assessment of a discontinued, now-pricey collector racket, not a current value pick.
            """),
            sec("The conical-shaft black tech", """
            The Shiden's defining feature, and what made it ahead of its time, is a tapered shaft that narrows from about 7.5mm at the cone to 6.7mm at the T-joint. That geometry was built to resolve the tension between shaft elasticity and anti-torsion, and Gosen reinforced it with Zylon fibre, the material used in body armour, and aircraft-grade Aermet nickel-cobalt alloy steel. The result is force-transmission efficiency the reviewer rates as hard to beat even now. For a buyer, the engineering explains the character that follows: this is a frame designed to deliver everything you put in, with nothing softened or forgiven along the way.
            """),
            sec("The downsides come first, honestly", """
            The reviewer leads with the flaws because they are unanimous among owners. The sweet spot is extraordinarily small, smaller even than a Z-Speed, so any off-centre contact produces obvious jarring and a hollow loss of power. The shaft is Gosen's hardest plus-three rating, effectively an iron bar with no spare flex. Tolerance is therefore extremely low: if your power is scattered, you will play badly with it, returns will float and smashes feel like hitting cotton. It offers nothing to paper over technique gaps. The honest buyer takeaway is that this racket demands consistent, concentrated, active power on every shot, or it will actively make you worse.
            """),
            sec("Net, drops and the hybrid-string fix", """
            Touch was historically the Shiden's weak area: with a single thin string the wrapping feel was poor and drop placement hard to control. The reviewer's hybrid setup, a higher-friction vertical string with an explosive cross, noticeably improves this, adding bite and a better pocket so drops gain control and net spins gain precision. It still does not match a dedicated control all-rounder such as an Arcsaber 10, but it crosses from frustrating to usable. The practical lesson generalises: if you own or chase one of these extreme small-frame blades, string choice is not a detail, it is the difference between a precise tool and an unforgiving one.
            """),
            sec("Point smashes, drives and the verdict", """
            Where the Shiden is untouchable is the point smash: hit the sweet spot and the shuttle leaves like a slingshot, instant release with zero drag, the best the reviewer has felt on any racket. Smashes are fast rather than heavy, with placement so quick the shuttle seems not to decelerate. Flat drives are its kingdom despite the 3U weight, the tiny swing weight and rigid shaft giving total mid-court control and a zero-delay, addictive feel. It is moody, state-dependent and high-ceilinged. As a purchase, accept that it is now a collector item with a steep premium: pursue it only if you have the technique to unlock it, and buy on authenticity and condition.
            """),
        ],
        "cta": CTA,
    },
    {
        "slug": "victor-fz-100xx-budget-attack-review",
        "updatedAt": DATE,
        "title": "Victor FZ-100XX review: a 100ZZ-styled budget attack racket that overdelivers",
        "dek": "The FZ line's 100XX copies the Astrox 100ZZ look and adds Victor's second-gen floating handle plus Whip Enhance 3.0: a wide box frame, forgiving mid-tier attack racket with a low skill floor.",
        "verdict": "A near-no-weakness mid-price attacker. It trades the high threshold of a flagship for accessibility, and still produces real smash power and continuity for the money. One of the stronger value attack picks in its band.",
        "sections": [
            sec("Where it sits: value attack done right", """
            Victor's FZ sub-line has built its identity on the mid-tier, chasing high specification at a low price, and the 100XX continues that brief as a budget answer to flagship attackers. The community framing is explicit, positioning it as an affordable stand-in for the kind of frame an aggressive singles or doubles player would want. We read that as a value claim to test, not a like-for-like equivalence with a flagship, so the right comparison is against other rackets in its own price band rather than against the much pricier models it borrows its looks from. On that basis, the reviewer rates it a clear over-performer.
            """),
            sec("Looks and frame", """
            The 100XX leans hard on Astrox 100ZZ styling and colourway, dropping the cheap plastic feel and busy graphics common at this price for a clean matte navy base with a silver gradient and a pearlescent throat that catches light. More important than the cosmetics is the structure: a fluid box-section large frame, wider than a traditional narrow attack head, which adds stability and meaningfully enlarges the sweet spot. That choice is the foundation of the racket's forgiveness, and it telegraphs the design intent, an attack frame engineered to be tolerant rather than punishing, which is exactly what a mid-tier buyer stepping up to a power racket needs.
            """),
            sec("Clears and transition: easy to drive", """
            Thanks to a slight head-heavy bias and a tough, elastic shaft, the reviewer found clears genuinely easy: passive baseline returns need no big swing, the frame's own weight and shaft rebound carrying the shuttle deep with a gentle pull. Under pressure on the rear court it resets cleanly and returns reliably to the opponent's back court rather than dumping short. Slices, drops and net touches are described as delicate, helped by the big sweet spot tolerating small power errors without wrecking quality. For an improving player, that low-effort baseline game is what makes a head-heavy frame approachable instead of exhausting.
            """),
            sec("Smash: the Whip Enhance 3.0 payoff", """
            Attack is the headline. The Whip Enhance 3.0 handle system, paired with the elastic shaft, lets the 100XX punch above its class. Small-power point smashes are fast and awkwardly placed for quick scoring, while full smashes load and snap the shaft into a concentrated, heavy, fast downward strike. The key difference from hardcore flagship attackers, which lean on absolute strength, is that the 100XX rewards technique and borrowed whip power, so an improving player without a huge arm can still produce a quality heavy smash. The box frame's stability also means continuous smashing does not wobble the head or scatter placement, supporting sustained pressure.
            """),
            sec("Drives, defence and the verdict", """
            In fast doubles exchanges the 100XX swings lightly and links smoothly, with crisp mid-range drives and none of the sluggishness you might fear from a head-heavy frame. Defence beat expectations: a stable frame, forgiving block-and-lift, and easy counter-drive transitions. The one honest limit is that in the very fastest pure-speed rallies it trails a dedicated speed racket on swing-through quickness, so this is a steady, strong-attack continuity frame rather than a pure speed weapon. For a mid-tier player who wants real attack with a low skill floor and a flagship look, it is an easy recommendation in its price band.
            """),
        ],
        "cta": CTA,
    },
    {
        "slug": "anta-ah600w-racket-review",
        "updatedAt": DATE,
        "title": "Anta AH600W review: a sportswear giant's first badminton racket, honestly assessed",
        "dek": "Anta's entry into rackets is a 5U/G6 (about 82g) balanced beginner blade: 299mm balance, mid-low stiffness, a 76-hole box frame, strung 24-26 lb. An OEM-built first effort that edges above 'nothing special'.",
        "verdict": "An honest entry-level all-rounder. Surprisingly drivable for an ultralight debut, but a stepping-stone rather than a destination, and most interesting as a sign that a major sportswear brand has entered the category.",
        "sections": [
            sec("The story is the brand, not the spec", """
            The headline here is that Anta, one of China's largest sportswear companies, has stepped into badminton rackets at all. The reviewer is blunt that the product itself is an entry-level, what-you-see-is-what-you-get frame with little to dissect: minimal graphics, sparse stickers and basic printed information on the box-section head. For a buyer, that candour is the useful part. This is not a hidden-gem flagship; it is a competent first racket from a brand with the distribution and budget to iterate. We treat the spec figures below as community-reported from the source review, since Anta does not yet publish detailed English specifications for the model.
            """),
            sec("Specs and a buying trap to avoid", """
            The tested AH600W is a 5U/G6 weighing about 82 grams in use, with a 299mm balance, a 220mm shaft of mid-low stiffness, a box-section frame, a 76-hole string bed, a 30 lb warranty and a 24-26 lb strung range on a budget string. The single most important buying note from the reviewer: the AH600 and AH600W are not just colour variants, they are different weights, 4U versus 5U respectively. Anyone shopping the line should confirm the exact code before purchase, because the handling difference between a 4U and a 5U is significant and easy to order wrong from a marketplace listing.
            """),
            sec("On court: a tidy balanced blade", """
            The reviewer describes a balanced, super-light, easy-to-start frame, and was mildly surprised that the ultralight build did not produce the borrow deficit such rackets often suffer. Drive feels above average for the class, and on active downward presses it even returns a little rebound energy, which the reviewer admits is more than expected from a brand new to the category. The honest read is that an OEM factory likely supplied a sound existing mould, but the outcome for a buyer is the same: it plays cleanly and predictably, lifts easily into defence, and lets a beginner generate enough pace to learn without fighting the racket.
            """),
            sec("The honest limits", """
            This is firmly an entry-level tool, and the reviewer's wider point is that frames like it have a low ceiling, fine for learning and casual play but not something an improving player will grow with. There is no special technology or standout shot here; it is competent rather than characterful. Durability and finish are basic, and long-term feedback from this tier of racket tends to plateau quickly. None of that is a criticism of the price, but a buyer should set expectations accordingly: pay entry-level money, get an honest entry-level racket, and plan to upgrade once technique outgrows it.
            """),
            sec("Who should buy it", """
            The AH600W makes sense for a true beginner or casual player who wants a light, forgiving, low-cost racket from a brand they recognise, especially someone already inside the Anta retail ecosystem. It is also a reasonable knock-about or spare. Improving players chasing a long-term frame should look at the established entry-and-mid-tier options from the specialist brands, which offer clearer upgrade paths and better support. As a debut, though, the AH600W is genuinely respectable, and worth watching as a signal that Anta intends to compete in badminton rather than dabble.
            """),
        ],
        "cta": CTA,
    },
    {
        "slug": "bonny-leisu-800-lt-review",
        "updatedAt": DATE,
        "title": "Bonny Leisu 800 LT review: a clear-named NF800LT tribute for continuous attack",
        "dek": "A 5U/G5 (about 85g, 305mm balance, mid-high stiffness, small box frame, 76 holes) with a nickel-titanium or boron shaft option. Bonny's most legible naming yet, openly channeling the discontinued Nanoflare 800 LT.",
        "verdict": "A precise, fast continuous-attack 5U. The small frame charges a real accuracy tax, but it delivers the NF800LT character at a sane, in-production price, which is the whole point.",
        "sections": [
            sec("Cutting through Bonny's naming fog", """
            Bonny's speed rackets have long played well but sat under the shadow of the Jiguang 800 Pro and a tangle of overlapping, hard-to-place model names that the reviewer openly criticises. The 800 LT is the exception: both its naming and its construction point unambiguously at the discontinued Nanoflare 800 LT, and rather than object to the homage, the reviewer credits Bonny for finally giving buyers information they cannot misread. For shoppers, that clarity matters: you know exactly what character you are buying before you commit, which is rare in this brand's catalogue and worth rewarding.
            """),
            sec("Build and the shaft-variant choice", """
            The tested 800 LT is a 5U/G5 weighing about 85 grams in use, with a high 305mm balance, a 217mm shaft of mid-high stiffness, a small box-section frame, a 76-hole bed, full string grooves, a 30 lb warranty and a 25-27 lb strung range. A genuinely useful detail: the colourways carry different shafts, with the tested rose-red version using a nickel-titanium shaft and the alternate using boron fibre, so the two finishes are tuned for different hand feels rather than being cosmetic twins. The vivid decals over black base paint also give it real visual presence. Choose the colour for the shaft, not just the look.
            """),
            sec("Core feel: firm, fast, concentrated", """
            The reviewer's overriding impression is that this plays exactly like the NF800LT memory: a firm overall tune, a high balance point that nonetheless swings fast for smooth power generation, and a high-tension, concentrated sweet spot with abundant burst. The box frame adds a payoff beyond raw elasticity, every clean contact flies along the line you intended, a stability that is uncommon in 5U frames. The honest cost is lower damping, which dents confidence on net shuttles and rear-court drops; the reviewer found it subjectively a touch too light for fine touch, so precise control work takes more care than on a more damped frame.
            """),
            sec("Drives and quick blocks", """
            Against the 800 Pro, which builds shots through a hold-and-load feel and a larger face, the LT is more decisive and crisp. Its response is fast, the power stroke short and effective, so racket-to-racket linking stays smooth and each drive carries strong penetration. The reviewer frames the pair as a choice: the Pro offers more tolerance and confident continuity through a bigger head, while the LT is the purer, more extreme expression of fast continuous play. For a player who lives in flat mid-court exchanges and wants immediacy over cushioning, the LT is the more exciting of the two.
            """),
            sec("Smash, the precision tax, and who it suits", """
            Continuous attack is the racket's backbone. The nickel-titanium shaft's toughness and high rebound let you whip-load smashes easily, with power and shuttle speed scaling linearly and each heavy smash arriving with both force and a satisfying crack, while the light build keeps follow-up attacks coming. The unavoidable trade-off, common to small frames, is precision: when active you can do no wrong, but low defensive lifts, backhand escapes and smash defence magnify the small loss of bed area. For attacking 5U players, especially anyone who missed the now-overpriced NF800LT, this is an accurate, in-production way to get that twin attack-and-speed feel.
            """),
        ],
        "cta": CTA,
    },
    {
        "slug": "mizuno-carbo-pro-825-review",
        "updatedAt": DATE,
        "title": "Mizuno Carbo Pro 825 review: the softer, stickier sibling to the 823",
        "dek": "A 4U/G5 (about 94g, 300mm balance, mid-low stiffness, fluid box frame, 72 holes, strung around 24 lb). Not the 'balanced' racket forums claim, but a less-extreme base attacker that is friendlier than the 823.",
        "verdict": "A forgiving, hold-on-ball attack frame with the series' premium looks. Better continuous play and defence than the 823, with weak flat drives; restring it firmer and it suits a wide range of players.",
        "sections": [
            sec("Placing the 825 in the Carbo Pro line", """
            The reviewer rounds off the regular-channel Carbo Pro range with the 825, and corrects a common assumption: it is not the same racket as the 823, and the differences are not small. The forum label of a balanced racket overstates it; the reviewer pegs it as a not-overly-extreme base attacking frame rather than a true all-rounder. It is also awkward to buy, with clearance channels often bundling it in pairs. As with the rest of this batch the specifications are community-reported, since Mizuno does not publish detailed English data for the model, but the on-court read is consistent and useful.
            """),
            sec("Looks and build", """
            The 825 keeps the line's signature styling, an Astrox-like asymmetric split with black up top and orange below, so close to the 823 in some promotional shots that the reviewer initially mistook the two box-frame rackets for one model. Whatever the colour, the series carries a more premium visual presence than most budget frames, which is a real part of its appeal at the price. Under the paint sits a 4U/G5 build at about 94 grams in use, a 300mm balance, a 218mm mid-low-stiffness shaft, a thinner, rounder fluid box-section frame, a 72-hole bed, 9-to-3 grooves, a 28 lb warranty and a modest strung tension.
            """),
            sec("Easier to use than the 823", """
            The headline improvement is accessibility. The 825's onboarding sits near the 829 and is easier than the 823: swing weight is still on the high side, but the thinner, rounder fluid box frame and a slightly lower overall stiffness noticeably cut the power impedance. With the same borrowed-power feel and the same unremarkable factory string, clears take less load and the release feels more agreeable, without the off-putting effort the 823 can demand. Frame stability is not sacrificed for that ease either, holding placement well through long, slow rallies, so the friendlier feel does not come at the cost of control.
            """),
            sec("Hold-on-ball control and a string caveat", """
            The fluid frame runs a slightly lower stringbed tension, giving a stronger hold-on-ball feel than both the 823 and 829, a stickier, more cushioned contact. That cuts both ways: at the net the heavy de-powering can over-soften touch shots, so the reviewer advises swapping in a firmer, livelier string and adapting to less push and more pop. The upside is excellent wrap-and-slice behaviour and a dependable sweet-spot area, making steep slice drops easy from the rear court along a natural downward flight, though confidence on the release dips slightly because the soft contact leaves you wondering if the shuttle cleared the net.
            """),
            sec("Attack, defence and the verdict", """
            Attack is sound rather than spectacular: the longer hold transmits swing power more fully into the shuttle, the natural downward bias helps, and a slightly lower-drag frame gives advancing players usable burst with good in-class power. Rear-court continuity beats the 823, and passive shuttles and smash defence feel more trustworthy under pressure. The clear weakness is front-court flat drives, where the green 829 with its aero frame remains the line's best. The reviewer ends up genuinely liking the 825 for its looks, feel and everyday match needs: restring it and it suits most male players across levels, and at this price the brand and finish alone justify the spend.
            """),
        ],
        "cta": CTA,
    },
]

def main():
    # 1) sprint articles
    sprint = json.loads(SPRINT.read_text(encoding="utf-8"))
    have = {a["slug"] for a in sprint}
    added = 0
    for art in ARTICLES:
        if art["slug"] in have:
            print("skip (exists in sprint):", art["slug"]); continue
        sprint.append(art); added += 1
    SPRINT.write_text(json.dumps(sprint, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    # 2) slugs list
    slugs = json.loads(SLUGS.read_text(encoding="utf-8"))
    for s in SOURCE_MAP:
        if s not in slugs:
            slugs.append(s)
    SLUGS.write_text(json.dumps(slugs, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    # 3) source map
    smap = json.loads(SMAP.read_text(encoding="utf-8"))
    for s, f in SOURCE_MAP.items():
        smap[s] = f
    SMAP.write_text(json.dumps(smap, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    # 4) archive the 2 skipped duplicate scrapes
    ARCHIVE.mkdir(exist_ok=True)
    moved = []
    for name in ARCHIVE_FILES:
        src = BLOGS / name
        if src.exists():
            shutil.move(str(src), str(ARCHIVE / name)); moved.append(name)

    # report
    allmd = {p.name for p in BLOGS.glob("*.md")}
    mapped = {v for v in smap.values() if v}
    unmapped = sorted(allmd - mapped)
    print(json.dumps({
        "sprint_added": added,
        "slugs_total": len(slugs),
        "sourcemap_total": len(smap),
        "archived": moved,
        "active_md": len(allmd),
        "unmapped_remaining": unmapped,
    }, ensure_ascii=False, indent=2))

if __name__ == "__main__":
    main()
